---
- name: Configure bird service
  service:
    name: bird
    enabled: "{{ bird_ipv4_config != [] }}"
    state: "{% if bird_ipv4_config != [] %}reloaded{% else %}stopped{% endif %}"

- name: Configure bird6 service
  service:
    name: bird6
    enabled: "{{ bird_ipv6_config != [] }}"
    state: "{% if bird_ipv6_config != [] %}reloaded{% else %}stopped{% endif %}"
